"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Loader2, ListChecks } from "lucide-react";
import { cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";
import { Checkbox } from "@/components/ui/checkbox";
import { useLeadFocus } from "@/lib/lead-focus";
import { CHECKLIST_LABELS } from "@/lib/lead-checklists";
import type { LeadChecklistCategory } from "@prisma/client";

/**
 * Checklists generated by the pipeline: documents at Qualified, then visa,
 * pre-departure and accommodation once a deposit is paid.
 */

interface Item {
  id: string;
  category: LeadChecklistCategory;
  label: string;
  isRequired: boolean;
  completedAt: string | null;
  document?: { id: string; name: string } | null;
}

const ORDER: LeadChecklistCategory[] = ["DOCUMENT", "VISA", "PRE_DEPARTURE", "ACCOMMODATION"];

export function ChecklistPanel({ leadId }: { leadId: string }) {
  const router = useRouter();
  const { toast } = useToast();
  const [items, setItems] = React.useState<Item[] | null>(null);
  const [busy, setBusy] = React.useState<string | null>(null);
  const rootRef = React.useRef<HTMLDivElement | null>(null);

  const load = React.useCallback(async () => {
    const res = await fetch(`/api/leads/${leadId}/checklist`);
    if (res.ok) setItems((await res.json()).items ?? []);
  }, [leadId]);

  React.useEffect(() => {
    load();
  }, [load]);

  /**
   * Scrolling is all this can do. The Qualified gate wants the document
   * checklist to EXIST, and it is generated by the server when the student
   * reaches Qualified rather than by anything the user can press here — so
   * there is no button to open, only a place to look.
   */
  useLeadFocus((target) => {
    if (target.where !== "checklist") return;
    rootRef.current?.scrollIntoView({ behavior: "smooth", block: "center" });
  });

  async function toggle(item: Item) {
    setBusy(item.id);
    try {
      const res = await fetch(`/api/leads/${leadId}/checklist`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ itemId: item.id, completed: !item.completedAt }),
      });
      if (!res.ok) {
        const d = await res.json().catch(() => ({}));
        toast({ title: d.error ?? "Could not update", variant: "destructive" });
        return;
      }
      await load();
      router.refresh();
    } finally {
      setBusy(null);
    }
  }

  // The three states below are wrapped in one element that is always mounted,
  // because the state the scroll target matters MOST in is the empty one — the
  // Qualified gate's checklist requirement is outstanding precisely when there
  // is nothing here yet. A ref on the populated branch alone would fail in the
  // only case that sends anyone here.
  if (items === null) {
    return (
      <div ref={rootRef}>
        <p className="text-xs text-slate-400 dark:text-slate-500 py-4 text-center">Loading…</p>
      </div>
    );
  }

  if (items.length === 0) {
    return (
      <div
        ref={rootRef}
        className="text-center py-6 border border-dashed border-slate-200 dark:border-slate-800 rounded-lg"
      >
        <ListChecks className="h-6 w-6 mx-auto text-slate-300 dark:text-slate-600 mb-2" />
        <p className="text-xs text-slate-400 dark:text-slate-500">
          Checklists appear automatically once the student reaches Qualified.
        </p>
      </div>
    );
  }

  const grouped = ORDER.map((category) => ({
    category,
    rows: items.filter((i) => i.category === category),
  })).filter((g) => g.rows.length > 0);

  return (
    <div className="space-y-5" ref={rootRef}>
      {grouped.map(({ category, rows }) => {
        const required = rows.filter((r) => r.isRequired);
        const doneRequired = required.filter((r) => r.completedAt).length;
        const pct = required.length ? Math.round((doneRequired / required.length) * 100) : 100;

        return (
          <div key={category}>
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs font-semibold text-slate-700 dark:text-slate-300">
                {CHECKLIST_LABELS[category]}
              </p>
              <span
                className={cn(
                  "text-[11px] font-medium tabular-nums",
                  pct === 100 ? "text-green-600 dark:text-green-400" : "text-slate-400 dark:text-slate-500"
                )}
              >
                {doneRequired}/{required.length} required
              </span>
            </div>

            <div className="h-1 rounded-full bg-slate-100 dark:bg-slate-800 mb-2.5 overflow-hidden">
              <div
                className={cn("h-full transition-all", pct === 100 ? "bg-green-500" : "bg-[#0EA5E9]")}
                style={{ width: `${pct}%` }}
              />
            </div>

            <div className="space-y-1">
              {rows.map((item) => (
                <label
                  key={item.id}
                  className="flex items-start gap-2.5 py-1 cursor-pointer group"
                >
                  {busy === item.id ? (
                    <Loader2 className="h-4 w-4 animate-spin text-slate-400 dark:text-slate-500 mt-0.5 shrink-0" />
                  ) : (
                    <Checkbox
                      checked={!!item.completedAt}
                      onCheckedChange={() => toggle(item)}
                      className="mt-0.5 shrink-0"
                    />
                  )}
                  <span
                    className={cn(
                      "text-xs leading-relaxed",
                      item.completedAt
                        ? "text-slate-400 dark:text-slate-500 line-through"
                        : "text-slate-700 group-hover:text-slate-900 dark:text-slate-300 dark:group-hover:text-slate-100"
                    )}
                  >
                    {item.label}
                    {!item.isRequired && (
                      <span className="text-slate-300 dark:text-slate-600 ml-1.5">optional</span>
                    )}
                  </span>
                </label>
              ))}
            </div>
          </div>
        );
      })}
    </div>
  );
}
